apiVersion: v1
kind: Service
metadata:
  name: transmission-ingress
  namespace: transmission
spec:
  ports:
  - port: 9091
    protocol: TCP
    targetPort: 9091
  sessionAffinity: None
  type: ClusterIP
