apiVersion: v1
kind: ConfigMap
metadata:
  name: transmission-config
  namespace: transmission
data:
  LOCAL_NETWORK: 10.0.0.0/8
  OPENVPN_CONFIG: CA Vancouver
  OPENVPN_OPTS: --inactive 3600 --ping 10 --ping-exit 60
  OPENVPN_PROVIDER: PIA
  TRANSMISSION_DOWNLOAD_QUEUE_SIZE: "4"
  TRANSMISSION_RATIO_LIMIT: "2"
  TRANSMISSION_RATIO_LIMIT_ENABLED: "true"
  TRANSMISSION_SPEED_LIMIT_DOWN: "10000"
  TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED: "true"
  TRANSMISSION_SPEED_LIMIT_UP: "1000"
  TRANSMISSION_SPEED_LIMIT_UP_ENABLED: "true"
  WEBPROXY_ENABLED: "false"
